apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kcd-2025-nginx.fullname" . }}-html
  labels:
    {{- include "kcd-2025-nginx.labels" . | nindent 4 }}
data:
  index.html.template: |
    <!doctype html>
    <html lang="ko">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>KCD 2025 Demo</title>
        <style>
          :root { --bg: #0b1021; --card: #111735; --txt: #e6e9f5; --sub: #9aa4c7; --accent: #4e8cff; --h2-size: clamp(22px, 4vw, 34px); }
          * { box-sizing: border-box; }
          body { margin: 0; background: radial-gradient(1200px 600px at 20% -10%, #17214a, #0b1021); color: var(--txt); font: 16px/1.6 system-ui, -apple-system, Segoe UI, Roboto, Noto Sans KR, Arial, sans-serif; }
          .wrap { min-height: 100vh; display: grid; place-items: center; padding: 24px; }
          .card { width: min(860px, 92vw); background: linear-gradient(180deg, rgba(255,255,255,0.04), rgba(255,255,255,0.02)); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 32px 28px; box-shadow: 0 20px 50px rgba(0,0,0,0.35); backdrop-filter: blur(6px); }
          .kicker { display:inline-block; padding: 4px 10px; border:1px solid rgba(255,255,255,0.18); border-radius:999px; color: var(--sub); font-size: 12px; letter-spacing: .06em; text-transform: uppercase; }
          h1 { margin: 14px 0 8px; font-size: clamp(22px, 4vw, 34px); letter-spacing: .01em; }
          h2 { font-size: var(--h2-size); margin: 10px 0 0; }
          .accent { color: var(--accent); font-weight: 700; }
          .muted { color: var(--sub); margin-top: 10px; font-size: 14px; }
          .date { margin-top: 20px; display: flex; align-items: center; gap: 12px; }
          .date-label { color: var(--sub); font-size: 12px; text-transform: uppercase; letter-spacing: .08em; border: 1px solid rgba(255,255,255,0.18); padding: 4px 10px; border-radius: 999px; }
          .date-value { font-size: var(--h2-size); font-weight: 700; letter-spacing: .01em; color: #fff; }
        </style>
      </head>
      <body>
        <main class="wrap">
          <section class="card">
            <div class="kicker">Cloud Native Korea Community Day 2025</div>
            <h1>[${PREFIX}-${REGION}]</h1>
            <h2><span class="accent">Cloud Native Korea Community Day 2025</span> 에 오신것을 환영합니다!</h2>
            <div class="date">
              <span class="date-label">Event Date</span>
              <span class="date-value">2025-09-16</span>
            </div>
          </section>
        </main>
      </body>
    </html>
