apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcd-2025-root-west
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kcd-2025
  source:
    repoURL: https://github.com/KKamJi98/kcd-2025.git
    targetRevision: HEAD
    path: argocd/app-of-apps/west
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
