apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcd-2025-east
  namespace: argocd
spec:
  project: kcd-2025
  source:
    repoURL: https://github.com/KKamJi98/helm-charts.git
    path: kcd_2025
    targetRevision: HEAD
    helm:
      releaseName: mookup
      parameters:
      - name: prefix
        value: kcd
      - name: region
        value: east
      - name: replicaCount
        value: "3"
  destination:
    name: kkamji-east
    namespace: kcd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
